# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0cabc8b2f4e1f0df56180abf424d02959202be8de7a902f7ea9aaa2e8c4a0b39b04ee8fa8e072e666008173e331f6e58d1b852e202db3f48f3c49e2e86602cf

test:
  secret_key_base: 250ba20f931ca35d766f1ed4a8def2fa78bc5eda85864f8fbf5b8ee9946c361c5140d9e023f9d3d7a15400cefaab9ed91820240084bbdeed116d8f546ce69b90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
